# REQUIREMENTS:
# 1. Share the same network as the host
# 2. GPU access
# 3. Display access
# 4. Zenoh and no zenoh support
# 5. Bind the repo 
# 6. Support hotplugging USB input
# 7. Read/write ability with serial microcontrollers
# 8. Real time scheduling enabled

name: tibble_redo

services:
  # This is the DEFAULT PROFILE of the tibble service
  # It assumes the iplink router is not being used but remote control is wanted
  # So it sets up Zenoh but not the router
  tibble_remote:
    extends:
      file: compose-base.yaml
      service: tibble_base

    container_name: tibble_remote

    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_CONFIG=/config/zenoh/remote.json5

  # This is the competition grade docker setup
  # It assumes the iplink router is being used with Zenoh
  tibble_competition:
    extends:
      file: compose-base.yaml
      service: tibble_base

    container_name: tibble_competition

    environment:
          - RMW_IMPLEMENTATION=rmw_zenoh_cpp
          - ZENOH_CONFIG=/config/zenoh/competition_client.json5
    
    # This profile is only used when composed with docker compose --profile competition up
    profiles:
      - competition
  
  # This service assumes you are only using one machine for development or using wired control
  tibble_wired:
    extends:
      file: compose-base.yaml
      service: tibble_base

    container_name: tibble_wired

    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

    profiles:
      - wired
