# REQUIREMENTS:
# 1. Share the same network as the host
# 2. GPU access
# 3. Display access
# 4. Zenoh and no zenoh support
# 5. Bind the repo 
# 6. Support hotplugging USB input
# 7. Read/write ability with serial microcontrollers
# 8. Real time scheduling enabled

name: tibble_redo
services:
  tibble_redo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host              # Share the same network stack as the host
    ipc: host                       # Prevents Fast DDS error with memory sharing
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - QT_QPA_PLATFORM=xcb
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_CONFIG_OVERRIDE=mode="client";connect/endpoints=["${ZENOH_ADDRESS}"]
    volumes:
      - type: bind                 # udev database
        source: /run/udev
        target: /run/udev
        read_only: true
      - type: bind
        source: ..
        target: /workspaces/tibble_redo
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: /dev/serial/by-id
        target: /dev/serial/by-id
        read_only: true
      - /dev:/dev
    cap_add:
      - SYS_NICE               # For real-time scheduling
    tty: true
    stdin_open: true
    group_add:
      - dialout
      - video
      - input